export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_USER = "SET_USER";
export const SET_STATE = "SET_STATE";
export const SET_LOADING = "SET_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_SONGS = "GET_SONGS";
export const GET_PLAYLISTS = "GET_PLAYLIST";
export const GET_ARTISTS = "GET_ARTISTS";
export const GET_ALBUMS = "GET_ALBUMS";
export const GET_USER_PLAYLISTS = "GET_USER_PLAYLISTS";
export const GET_FEATURED_PLAYLISTS = "GET_FEATURED_PLAYLISTS";
export const GET_USER_TOP_TRACKS = "GET_USER_TOP_TRACKS";
export const GET_USER_TOP_ARTISTS = "GET_USER_TOP_ARTISTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_NEW_RELEASES = "GET_NEW_RELEASES";
export const GET_USER_FOLLOWED_ARTISTS = "GET_USER_FOLLOWED_ARTISTS";
export const GET_USER_SAVED_TRACKS = "GET_USER_SAVED_TRACKS";
export const GET_USER_SAVED_ALBUMS = "GET_USER_SAVED_ALBUMS";
export const GET_RECENTLY_PLAYED = "GET_RECENTLY_PLAYED";
export const GET_CATEGORIES_DETAIL = "GET_CATEGORIES_DETAIL";
export const GET_CHARTS = "GET_CHARTS";
export const GET_RECOMMENDATIONS_WITH_SEEDS = "GET_RECOMMENDATIONS_WITH_SEEDS";
export const GET_RELATED_ARTISTS = "GET_RELATED_ARTISTS";
export const GET_RELATED_TRACKS = "GET_RELATED_TRACKS";
